version: "2"
services:
  server:
    image: jgreat/rancher-gluster-server:3.12.0-0
    cap_add:
      - SYS_ADMIN
      - MKNOD
    volumes:
      - glusterfs-server-data:/bricks/data
      - glusterfs-server-config:/var/lib/glusterd
    volume_driver: local
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: storage=gluster
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
